export const levels = [
  {
    id: 1,
    title: "Kezdő alapok",
    description: "Egyszerű, mindennapi kifejezések.",
    sentences: [
      { hu: "Jó reggelt!", en: "Good morning!" },
      { hu: "Jó estét!", en: "Good evening!" },
      { hu: "Szia!", en: "Hi!" },
      { hu: "Viszlát!", en: "Bye!" },
      { hu: "Hogy vagy?", en: "How are you?" },
      { hu: "Jól vagyok.", en: "I am fine." },
      { hu: "Köszönöm szépen.", en: "Thank you very much." },
      { hu: "Köszönöm.", en: "Thank you." },
      { hu: "Szívesen.", en: "You're welcome." },
      { hu: "Bocsánat.", en: "Sorry." },
      { hu: "Elnézést.", en: "Excuse me." },
      { hu: "Nem értem.", en: "I don't understand." },
      { hu: "Értem.", en: "I understand." },
      { hu: "Hogy hívnak?", en: "What is your name?" },
      { hu: "A nevem Dániel.", en: "My name is Daniel." },
      { hu: "Honnan jöttél?", en: "Where are you from?" },
      { hu: "Magyarországról jöttem.", en: "I am from Hungary." },
      { hu: "Örülök, hogy megismertelek.", en: "Nice to meet you." },
      { hu: "Igen.", en: "Yes." },
      { hu: "Nem.", en: "No." },
      { hu: "Talán.", en: "Maybe." },
      { hu: "Persze.", en: "Of course." },
      { hu: "Kérem.", en: "Please." },
      { hu: "Segíts!", en: "Help!" },
      { hu: "Várj egy pillanatot.", en: "Wait a moment." },
      { hu: "Gyere ide.", en: "Come here." },
      { hu: "Menjünk!", en: "Let's go!" },
      { hu: "Ez mi?", en: "What is this?" },
      { hu: "Az mi?", en: "What is that?" },
      { hu: "Ez jó.", en: "This is good." },
      { hu: "Ez rossz.", en: "This is bad." },
      { hu: "Nagyon jó!", en: "Very good!" },
      { hu: "Nem tudom.", en: "I don't know." },
      { hu: "Tudom.", en: "I know." },
      { hu: "Készen vagyok.", en: "I am ready." },
      { hu: "Nem vagyok kész.", en: "I am not ready." },
      { hu: "Most megyek.", en: "I am going now." },
      { hu: "Mindjárt jövök.", en: "I will be right back." },
      { hu: "Hol vagy?", en: "Where are you?" },
      { hu: "Itt vagyok.", en: "I am here." },
    ],
  },
  {
    id: 2,
    title: "Alapvető kifejezések",
    description: "Bevásárlás, étterem, közlekedés.",
    sentences: [
      { hu: "Mennyibe kerül ez?", en: "How much does this cost?" },
      { hu: "Ez túl drága.", en: "This is too expensive." },
      { hu: "Van olcsóbb?", en: "Do you have a cheaper one?" },
      { hu: "Kérek egy kávét.", en: "I would like a coffee." },
      { hu: "Kérek egy teát.", en: "I would like a tea." },
      { hu: "Kérek egy pohár vizet.", en: "I would like a glass of water." },
      { hu: "Mit ajánl?", en: "What do you recommend?" },
      { hu: "Mit szeretnél enni?", en: "What would you like to eat?" },
      { hu: "Finom volt az étel.", en: "The food was delicious." },
      { hu: "Kérem a számlát.", en: "Can I have the bill?" },
      { hu: "Kártyával fizetek.", en: "I pay by card." },
      { hu: "Készpénzzel fizetek.", en: "I pay in cash." },
      { hu: "Hol van a mosdó?", en: "Where is the restroom?" },
      { hu: "Hol van a buszmegálló?", en: "Where is the bus stop?" },
      { hu: "Hol van az állomás?", en: "Where is the station?" },
      { hu: "Eltévedtem.", en: "I am lost." },
      { hu: "Tudna segíteni?", en: "Could you help me?" },
      { hu: "Egy jegyet kérek.", en: "One ticket, please." },
      { hu: "Két jegyet kérek.", en: "Two tickets, please." },
      { hu: "Mikor indul a busz?", en: "When does the bus leave?" },
      { hu: "Mennyi az idő?", en: "What time is it?" },
      { hu: "Most hány óra van?", en: "What time is it now?" },
      { hu: "Korán van.", en: "It is early." },
      { hu: "Késő van.", en: "It is late." },
      { hu: "Szeretek kávét inni reggel.", en: "I like to drink coffee in the morning." },
      { hu: "Nem beszélek jól angolul.", en: "I don't speak English well." },
      { hu: "Beszél lassabban, kérem.", en: "Please speak more slowly." },
      { hu: "Megismételné?", en: "Could you repeat that?" },
      { hu: "Értem, köszönöm.", en: "I understand, thank you." },
      { hu: "Még egyet kérek.", en: "I would like another one." },
      { hu: "Ez minden.", en: "That's all." },
      { hu: "Csak nézelődöm.", en: "I am just looking." },
      { hu: "Felpróbálhatom?", en: "Can I try it on?" },
      { hu: "Van nagyobb méret?", en: "Do you have a bigger size?" },
      { hu: "Van kisebb?", en: "Do you have a smaller one?" },
      { hu: "Hol találom ezt?", en: "Where can I find this?" },
      { hu: "Ez nagyon jó.", en: "This is very good." },
      { hu: "Ez nem tetszik.", en: "I don't like this." },
      { hu: "Készen állok.", en: "I am ready." },
      { hu: "Indulhatunk.", en: "We can go." },
    ],
  },
  {
    id: 3,
    title: "Mindennapi társalgás",
    description: "Hosszabb, természetes mondatok.",
    sentences: [
      { hu: "Ma este moziba megyek a barátaimmal.", en: "Tonight I am going to the cinema with my friends." },
      { hu: "Általában hétkor kelek fel.", en: "I usually wake up at seven." },
      { hu: "Mit csinálsz a hétvégén?", en: "What are you doing this weekend?" },
      { hu: "Esik az eső, hozz egy esernyőt.", en: "It is raining, bring an umbrella." },
      { hu: "Holnap találkozunk a parkban.", en: "We are meeting in the park tomorrow." },
      { hu: "Szeretném megtanulni ezt a nyelvet.", en: "I would like to learn this language." },
      { hu: "Régóta nem láttalak.", en: "I haven't seen you in a long time." },
      { hu: "Mindig elfelejtem a nevét.", en: "I always forget his name." },
      { hu: "Jobban érzem magam.", en: "I feel better." },
      { hu: "Ma nagyon elfoglalt vagyok.", en: "I am very busy today." },
      { hu: "Most dolgozom.", en: "I am working now." },
      { hu: "Este edzeni megyek.", en: "I am going to work out in the evening." },
      { hu: "Szeretek utazni.", en: "I like to travel." },
      { hu: "Gyakran nézek filmeket.", en: "I often watch movies." },
      { hu: "Mit szeretsz csinálni?", en: "What do you like to do?" },
      { hu: "Hol dolgozol?", en: "Where do you work?" },
      { hu: "Frontend fejlesztő vagyok.", en: "I am a frontend developer." },
      { hu: "Most egy új projekten dolgozom.", en: "I am working on a new project now." },
      { hu: "Szeretem a kihívásokat.", en: "I like challenges." },
      { hu: "Ez nagyon érdekes.", en: "This is very interesting." },
      { hu: "Nem volt könnyű.", en: "It was not easy." },
      { hu: "Sokat tanultam belőle.", en: "I learned a lot from it." },
      { hu: "Mit gondolsz erről?", en: "What do you think about this?" },
      { hu: "Szerintem ez jó ötlet.", en: "I think this is a good idea." },
      { hu: "Nem értek egyet.", en: "I don't agree." },
      { hu: "Egyetértek.", en: "I agree." },
      { hu: "Beszéljünk róla később.", en: "Let's talk about it later." },
      { hu: "Most nincs időm.", en: "I don't have time now." },
      { hu: "Majd visszahívlak.", en: "I will call you back later." },
      { hu: "Írj nekem.", en: "Write to me." },
      { hu: "Küldök egy üzenetet.", en: "I will send a message." },
      { hu: "Hol találkozunk?", en: "Where do we meet?" },
      { hu: "Mikor kezdjük?", en: "When do we start?" },
      { hu: "Ez nagyon hasznos.", en: "This is very useful." },
      { hu: "Nem működik.", en: "It doesn't work." },
      { hu: "Megoldom.", en: "I will solve it." },
      { hu: "Segítek neked.", en: "I will help you." },
      { hu: "Köszönöm a segítséget.", en: "Thank you for the help." },
      { hu: "Nagyon hálás vagyok.", en: "I am very grateful." },
    ],
  },
  {
    id: 4,
    title: "Munkahelyi szókincs",
    description: "Iroda, megbeszélések, fejlesztés.",
    sentences: [
      { hu: "Holnap reggel megbeszélésünk lesz.", en: "We have a meeting tomorrow morning." },
      { hu: "Elküldenéd nekem a jelentést?", en: "Could you send me the report?" },
      { hu: "Dolgozom rajta.", en: "I am working on it." },
      { hu: "Kész van a feladat.", en: "The task is done." },
      { hu: "Tesztelni kell.", en: "It needs to be tested." },
      { hu: "Van egy bug a rendszerben.", en: "There is a bug in the system." },
      { hu: "Meg kell javítani.", en: "It needs to be fixed." },
      { hu: "Deployoljuk ma.", en: "We deploy today." },
      { hu: "Review-ra küldtem.", en: "I sent it for review." },
      { hu: "Pull requestet nyitottam.", en: "I opened a pull request." },
      { hu: "Átnéznéd?", en: "Could you review it?" },
      { hu: "Refaktorálni kell a kódot.", en: "The code needs refactoring." },
      { hu: "Nem skálázható.", en: "It is not scalable." },
      { hu: "Optimalizálni kell.", en: "It needs optimization." },
      { hu: "Beszéljünk a részletekről.", en: "Let's discuss the details." },
      { hu: "Mi a határidő?", en: "What is the deadline?" },
      { hu: "Elcsúsztunk.", en: "We are delayed." },
      { hu: "Időben elkészül.", en: "It will be done on time." },
      { hu: "Ez prioritás.", en: "This is a priority." },
      { hu: "Ez nem sürgős.", en: "This is not urgent." },
      { hu: "Frissítettem a dokumentációt.", en: "I updated the documentation." },
      { hu: "Egyeztetnünk kell.", en: "We need to align." },
      { hu: "Mi a következő lépés?", en: "What is the next step?" },
      { hu: "Átütemezzük.", en: "We reschedule." },
      { hu: "Visszajelzést adok.", en: "I will give feedback." },
      { hu: "Köszönöm a visszajelzést.", en: "Thank you for the feedback." },
      { hu: "Ez jól működik.", en: "This works well." },
      { hu: "Ez problémás.", en: "This is problematic." },
      { hu: "Megoldást keresünk.", en: "We are looking for a solution." },
      { hu: "Egyeztessünk a csapattal.", en: "Let's align with the team." },
      { hu: "Daily standup kezdődik.", en: "The daily standup is starting." },
      { hu: "Frissítettem a ticketet.", en: "I updated the ticket." },
      { hu: "Blockerbe ütköztem.", en: "I ran into a blocker." },
      { hu: "Segítségre van szükségem.", en: "I need help." },
      { hu: "Megoldottam.", en: "I solved it." },
      { hu: "Deploy sikeres volt.", en: "The deploy was successful." },
      { hu: "Rollbackoltunk.", en: "We rolled back." },
      { hu: "Monitoringot nézem.", en: "I am checking monitoring." },
      { hu: "Minden rendben.", en: "Everything is fine." },
    ],
  },
  {
    id: 5,
    title: "Haladó nyelvtan",
    description: "Összetett szerkezetek és árnyalatok.",
    sentences: [
      { hu: "Bárcsak több időm lenne.", en: "I wish I had more time." },
      { hu: "Ha tudtam volna, szóltam volna.", en: "If I had known, I would have told you." },
      { hu: "Annak ellenére, hogy fáradt volt, dolgozott.", en: "Although he was tired, he worked." },
      { hu: "Minél többet tanulsz, annál jobb leszel.", en: "The more you study, the better you become." },
      { hu: "Nem csak okos, hanem kitartó is.", en: "Not only is he smart, but also persistent." },
      { hu: "Azt mondta, hogy később jön.", en: "He said he would come later." },
      { hu: "Ha lenne időm, többet utaznék.", en: "If I had time, I would travel more." },
      { hu: "Ez a könyv már meg lett írva.", en: "This book has already been written." },
      { hu: "Mire odaértem, már elment.", en: "By the time I arrived, he had left." },
      { hu: "Lehet, hogy igazad van.", en: "You might be right." },
      { hu: "Biztosan tudja.", en: "He must know." },
      { hu: "Nem kellett volna ezt mondanom.", en: "I shouldn't have said that." },
      { hu: "Meg kellett volna csinálnom.", en: "I should have done it." },
      { hu: "Valószínűleg késni fog.", en: "He will probably be late." },
      { hu: "Nem biztos, hogy eljön.", en: "He might not come." },
      { hu: "Ez lehetetlennek tűnik.", en: "This seems impossible." },
      { hu: "Alig várom, hogy találkozzunk.", en: "I can't wait to meet." },
      { hu: "Úgy tűnik, működik.", en: "It seems to work." },
      { hu: "Az a célom, hogy fejlődjek.", en: "My goal is to improve." },
      { hu: "Fontos, hogy megértsd.", en: "It is important that you understand." },
      { hu: "Elképzelhető, hogy változik.", en: "It may change." },
      { hu: "Nem hiszem, hogy ez jó ötlet.", en: "I don't think this is a good idea." },
      { hu: "Úgy gondolom, hogy igazad van.", en: "I think you are right." },
      { hu: "Ha ezt teszed, sikeres leszel.", en: "If you do this, you will succeed." },
      { hu: "Amint kész, szólok.", en: "As soon as it is ready, I will let you know." },
      { hu: "Mielőtt elmennél, beszéljünk.", en: "Before you leave, let's talk." },
      { hu: "Miután befejeztem, hazamentem.", en: "After I finished, I went home." },
      { hu: "Még nem döntöttem.", en: "I haven't decided yet." },
      { hu: "Már régóta dolgozom rajta.", en: "I have been working on it for a long time." },
      { hu: "Folyamatosan fejlődöm.", en: "I am constantly improving." },
      { hu: "Ez nagy hatással volt rám.", en: "This had a big impact on me." },
      { hu: "Ez teljesen megváltoztatta a nézőpontomat.", en: "This completely changed my perspective." },
      { hu: "Ez nem az, amire számítottam.", en: "This is not what I expected." },
      { hu: "Pont erre volt szükségem.", en: "This is exactly what I needed." },
      { hu: "Ez sokkal jobb, mint gondoltam.", en: "This is much better than I thought." },
      { hu: "Ez sokkal nehezebb, mint vártam.", en: "This is much harder than I expected." },
      { hu: "Megéri az erőfeszítést.", en: "It is worth the effort." },
      { hu: "Ez hosszú távon kifizetődik.", en: "This pays off in the long run." },
    ],
  },
];